### ISSUE TITLE
grpc_Service should not be capitalized.

### ISSUE THREAD

**Issue by hesingon** [lchenn/py-grpc-prometheus#26]
https://github.com/lchenn/py-grpc-prometheus/blob/f0b06315eb1d9b27e6ed818bf4ded51e30d78624/py_grpc_prometheus/prometheus_client_interceptor.py#L173

`grpc_Service` should be `grpc_service`, else it will raise "Incorrect label names" when client interceptor is triggered.

**Comment by lchenn** [comment]
Fixed it with https://github.com/lchenn/py-grpc-prometheus/pull/27, released it with version 0.7.0. Thanks for raising the issue.
